### ISSUE TITLE
"Show only installed packages" displays error with no packages installed

### ISSUE THREAD

**Issue by cwollenhaupt** [DougHennig/FoxGet#9]
## 📝 Provide detailed reproduction steps (if any)

1. Create an empty project
2. Start FoxGet
3. Check the "show only installed packages" checkbox

### ✔️ Expected result

An empty list

### ❌ Actual result

A "Record is out of range" error dialog.

## 📷 Screenshots

<img width="818" alt="image" src="https://github.com/user-attachments/assets/31fc9d4a-e8f1-46f5-9ec1-790211798f2c">

**Comment by mikemeer** [comment]
Here is another screen shot for this bug.
![2024-09-28_FoxGet](https://github.com/user-attachments/assets/9730ea87-22c5-4b4f-88b9-f84488f0a764)

**Comment by DougHennig** [comment]
Fixed in the latest build.
